export const claims = {
    "english": {
        "voiladocPID": "VoiladocPID",
        "name": "Name",
        "phoneNo": "Phone No",
        "emailID": "Email ID",
        "insuranceCompany": "Insurance Company",
        "policyNumber": "Policy No",
        "subscripNo": "Subscription No",
        "claimAmount": "Claim Amount",
        "status": "Status",
        "attachments": "Attachments",
        "dashboard": "dashboard",
        "reason": "Reason",
        "ClaimsRaised": "Claims Raised",
        "ClaimsInProgress": "Claims In Progress",
        "ClaimsProcessed": "Claims Processed",
        "ClaimsRejected": "Claims Rejected",
    },
    "french": {
        "voiladocPID": "VoiladocPID",
        "name": "nom",
        "phoneNo": "Pas de téléphone",
        "emailID": "Identifiant de messagerie",
        "insuranceCompany": "Compagnie d'assurance",
        "policyNumber": "Numéro de police",
        "subscripNo": "Abonnement Non",
        "claim Amount": "Montant de la réclamation",
        "status": "statut",
        "attachments": "Pièces jointes",
        "dashboard": "dashboard",
        "reason": "Raison",
        "ClaimsRaised": "Revendications soulevées",
        "ClaimsInProgress": "Réclamations en cours",
        "ClaimsProcessed": "Réclamations traitées",
        "ClaimsRejected": "Réclamations rejetées",
    }
}