export const patient = {
        "english": {
                "name": "Name",
                "telephone": "Telephone",
                "email": "EmailID",
                "gender": "Gender",
                "address": "Address",
                "actions": "Actions",
                "add": "Add",
                "firstName": "First Name",
                "lastName": "Last Name",
                "dateOfBirth": "Date Of Birth",
                "identityNumber": "Identity Number",
                "insuranceCompanyName": "Insurance Company Name",
                "policyNumber": "Policy Number",
                "subscriptionNumber": "Subscription Number",
                "policyExpiryDate": "Policy Expiry Date",
                "save": "Save",
                "back": "Back",
                "dashboard": "Uploaded Patients",
                "up": "Upload Patient",
                "ClaimsRaised": "Claims Raised",
                "ClaimsInProgress": "Claims In Progress",
                "ClaimsProcessed": "Claims Processed",
                "ClaimsRejected": "Claims Rejected",
                "Dashboard": "Dashboard",
                "patients":"Patients"
        },
        "french": {
                "name": "Nom",
                "telephone": "Téléphone",
                "email": "EmailID",
                "gender": "Sexe",
                "address": "Adresse",
                "actions": "Actions",
                "add": "Ajouter",
                "firstName": "prénom",
                "lastName": "nom de famille",
                "dateOfBirth": "Date de naissance",
                "identityNumber": "numéro d'identité",
                "insuranceCompanyName": "Nom de la compagnie d'assurance",
                "policyNumber": "numéro de police",
                "subscriptionNumber": "Numéro d'abonnement",
                "policyExpiryDate": "Date d'expiration de la police",
                "save": "Sauvegarder",
                "back": "Retour",
                "dashboard": "Patients téléchargés",
                "up": "Télécharger un patient",
                "ClaimsRaised": "Revendications soulevées",
                "ClaimsInProgress": "Réclamations en cours",
                "ClaimsProcessed": "Réclamations traitées",
                "ClaimsRejected": "Réclamations rejetées",
                "Dashboard": "Tableau de bord",
                "patients":"les patients"
        }
}
