export const patient = {
    "english": {
        "name": "Name",
        "telephone": "Telephone",
        "email": "EmailID",
        "gender": "Gender",
        "address": "Address",
        "actions": "Actions",
        "add": "Add",
        "firstName": "First Name",
        "lastName": "Last Name",
        "dateOfBirth": "date Of Birth",
        "identityNumber": "Identity Number",
        "insuranceCompanyName": "Insurance CompanyName",
        "policyNumber": "Policy Number",
        "subscriptionNumber": "Subscription Number",
        "policyExpiryDate": "Policy Expiry Date",
        "save": "Save",
        "back": "Back",
    },
    "french": {
        "name": "Nom",
        "telephone": "Téléphone",
        "email": "EmailID",
        "gender": "Sexe",
        "address": "Adresse",
        "actions": "Actions",
        "add": "Ajouter",
        "firstName": "prénom",
        "lastName": "nom de famille",
        "dateOfBirth": "date de naissance",
        "identityNumber": "numéro d'identité",
        "insuranceCompanyName": "Nom de la compagnie d'assurance",
        "policyNumber": "numéro de police",
        "subscriptionNumber": "Numéro d'abonnement",
        "policyExpiryDate": "Date d'expiration de la police",
        "save": "Sauvegarder",
        "back": "Retour",
    }
}
